---
- hosts: myhosts
  connection: local
  name: Get firmware inventory
  gather_facts: False

  vars:
    datatype: FirmwareInventory

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml

  - name: Get firmware inventory
    redfish_info:
      category: Update
      command: GetFirmwareInventory
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 20
    register: result

  - name: Copy results to output file
    copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
