---
- hosts: myhosts
  connection: local
  name: Set boot mode to legacy and reboot
  gather_facts: False

  vars:
  - attribute_name: BootModes_SystemBootMode
  - attribute_value: LegacyMode

  tasks:

  - name: Get system model
    include_tasks: get_system_model.yml

  - name: update attribute_name and attribute_value for SR635/SR655
    set_fact:
      attribute_name: Q00001_Boot_Mode
      attribute_value: Legacy_only
    when: system_model == "ThinkSystem SR635" or system_model == "ThinkSystem SR655"

  - name: Set {{ attribute_name }} to {{ attribute_value }}
    redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attribute_name: "{{ attribute_name }}"
      bios_attribute_value: "{{ attribute_value }}"
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 20
  
  - name: Reboot system to apply new BIOS settings
    redfish_command:
      category: Systems
      command: PowerReboot
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 20
    when: bios_attribute.changed
